-- SELECT
--     B.AUTHOR_ID,
--     B.AUTHOR_NAME,
--     A.CATEGORY,
--     SUM(A.PRICE * C.SALES) AS TOTAL_SALES
-- FROM
--     BOOK A, 
--     AUTHOR B, 
--     BOOK_SALES C
-- WHERE
--     TO_CHAR(C.SALES_DATE, 'YYYYMM') = '202201'
--     AND A.AUTHOR_ID = B.AUTHOR_ID
--     AND A.BOOK_ID = C.BOOK_ID
-- GROUP BY
--     B.AUTHOR_ID,
--     B.AUTHOR_NAME,
--     A.CATEGORY
-- ORDER BY
--     B.AUTHOR_ID ASC,
--     A.CATEGORY DESC;


SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS "TOTAL_SALES"
FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;