-- SELECT CART_ID
-- FROM ( SELECT DISTINCT CART_ID, NAME
--        FROM CART_PRODUCTS
--        WHERE NAME IN ('Milk', 'Yogurt'))
-- GROUP BY CART_ID
-- HAVING COUNT(*) >= 2
-- ORDER BY CART_ID;

-- SELECT CART_ID, COUNT(*)
-- FROM CART_PRODUCTS
-- WHERE NAME IN ('Milk', 'Yogurt')
-- GROUP BY CART_ID
-- HAVING COUNT(*) >= 2
-- ORDER BY CART_ID;

-- SELECT CART_ID
-- FROM CART_PRODUCTS
-- WHERE NAME IN ('Milk', 'Yogurt')
-- GROUP BY CART_ID, NAME
-- HAVING COUNT(*) >= 2
-- ORDER BY CART_ID;

-- SELECT *
-- FROM CART_PRODUCTS
-- WHERE NAME IN ('Milk', 'Yogurt')


-- SELECT 
-- FROM (
--      SELECT DISTINCT(CART_ID) 
--      FROM CART_PRODUCTS
--      WHERE NAME IN ('Milk', 'Yogurt')
--      )

-- ;
SELECT CART_ID
FROM (
     SELECT DISTINCT(CART_ID), NAME, PRICE 
     FROM CART_PRODUCTS
     WHERE NAME IN ('Milk', 'Yogurt')
     )
GROUP BY CART_ID
HAVING COUNT(*) >= 2
ORDER BY CART_ID;





