SELECT CA.CART_ID
  FROM CART_PRODUCTS CA
     , (
         SELECT CART_ID, COUNT(*) AS COUNT
         FROM CART_PRODUCTS
         WHERE NAME LIKE 'Yog%'
         GROUP BY CART_ID
         HAVING COUNT(*) = 1
     ) YO
     , (
         SELECT CART_ID, COUNT(*) AS COUNT
         FROM CART_PRODUCTS
         WHERE NAME LIKE 'Mil%'
         GROUP BY CART_ID
         HAVING COUNT(*) = 1
     ) MK
WHERE CA.CART_ID = YO.CART_ID
  AND CA.CART_ID = MK.CART_ID
 GROUP BY CA.CART_ID
 ORDER BY CA.CART_ID