SELECT EXTRACT (MONTH FROM START_DATE), CAR_ID, COUNT(*) AS "RECORDS"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 1=1
AND TO_CHAR(START_DATE, 'YYYY-MM-DD') >= '2022-08-01'
AND TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-31'
AND CAR_ID IN (SELECT DISTINCT CAR_ID
               FROM
                   (SELECT CAR_ID, COUNT(*)
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE 1=1
                    AND TO_CHAR(START_DATE, 'YYYY-MM-DD') >= '2022-08-01'
                    AND TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-31'
                    GROUP BY CAR_ID
                    HAVING COUNT(*) >= 5))
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY EXTRACT(MONTH FROM START_DATE) ASC, CAR_ID DESC;

