-- SELECT 
--     I.ANIMAL_ID, 
--     I.NAME
-- FROM 
--     ANIMAL_INS I, ANIMAL_OUTS O
-- WHERE 
--     I.ANIMAL_ID = O.ANIMAL_ID (+)
--     AND I.DATETIME <= O.DATETIME
-- ORDER BY 
--     O.DATETIME - I.DATETIME DESC
-- FETCH FIRST 2 ROWS ONLY;

-- SELECT *
-- FROM (SELECT I.ANIMAL_ID, I.NAME, O.DATETIME - I.DATETIME AS "DURATION"
--       FROM ANIMAL_INS I
--       JOIN ANIMAL_OUTS O
--       ON I.ANIMAL_ID = O.ANIMAL_ID)
-- ORDER BY DURATION DESC
-- FETCH FIRST 2 ROWS ONLY;


SELECT ANIMAL_ID, NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, O.DATETIME - I.DATETIME AS "DURATION"
      FROM ANIMAL_INS I
      JOIN ANIMAL_OUTS O
      ON I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY DURATION DESC
FETCH FIRST 2 ROWS ONLY;