-- --day와 duration_type 을 조건으로 join하여 discount_rate를 구함
-- SELECT C.CAR_ID,
--                C.CAR_TYPE,
--                C.DAILY_FEE,
--                CASE WHEN H.END_DATE - H.START_DATE + 1 >= 90 THEN '90일 이상'
--                     WHEN H.END_DATE - H.START_DATE + 1 >= 30 THEN '30일 이상'
--                     WHEN H.END_DATE - H.START_DATE + 1 >= 7 THEN '7일 이상'
--                ELSE '7일 미만'
--                END AS DURATION_TYPE
--           FROM CAR_RENTAL_COMPANY_CAR C
--          INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
--             ON C.CAR_ID = H.CAR_ID
--          WHERE C.CAR_TYPE IN ('세단', 'SUV')
--                AND
--                C.CAR_ID NOT IN (SELECT CAR_ID
--                                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--                                  WHERE H.START_DATE <= DATE '2022-11-30'
--                                        AND
--                                        H.END_DATE >= DATE '2022-11-01')

--
-- (H.START_DATE <= TO_DATE(20221101, 'YYYY-MM-DD') AND TO_DATE(20221201, 'YYYY-MM-DD') < H.END_DATE );
-- END_DATE < TO_DATE(20221101, 'YYYY-MM-DD') OR START_DATE >= TO_DATE(20221201, 'YYYY-MM-DD'); 대여 가능
-- 대여중

-- 원가에서 빼야한다.
-- 1000 - (1000 * (10 / 100))
-- (C.DAILY_FEE * ( 1 - P.DISCOUNT_RATE) * 30)
-- AND (C.DAILY_FEE - ( C.DAILY_FEE * P.DISCOUNT_RATE) * 30) BETWEEN 500000 AND 1999999
-- (DAILY_FEE * 30) * (100 - DISCOUNT_RATE) / 100
-- 정가 x (100% - 5%): 10000/100 - 5/100 

-- SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100  AS "FEE"
-- FROM CAR_RENTAL_COMPANY_CAR C
-- JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
-- ON C.CAR_ID = H.CAR_ID
-- JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
-- ON C.CAR_TYPE = P.CAR_TYPE
-- WHERE 1 =1 
-- AND C.CAR_TYPE IN ('세단', 'SUV')
-- AND P.DURATION_TYPE = '30일 이상'
-- AND (START_DATE < TO_DATE(20221201, 'YYYY-MM-DD') AND END_DATE >= TO_DATE(20221101, 'YYYY-MM-DD'))
-- AND (C.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100 >= 500000 
-- AND (C.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100 < 2000000
-- ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;

SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100  AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE 1 = 1 
AND CAR_ID NOT IN (
                  SELECT CAR_ID 
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE END_DATE > TO_DATE(20221101, 'YYYY-MM-DD'))
AND C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE = '30일 이상'
AND (C.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100 >= 500000 
AND (C.DAILY_FEE * 30) * (100 - P.DISCOUNT_RATE) / 100 < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;