SELECT F.FOOD_TYPE, I.REST_ID, I.REST_NAME, F.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS "FAVORITES" 
      FROM REST_INFO 
      GROUP BY FOOD_TYPE) F
JOIN REST_INFO I 
ON F.FOOD_TYPE = I.FOOD_TYPE
WHERE F.FAVORITES = I.FAVORITES
ORDER BY F.FOOD_TYPE DESC;