-- SELECT B.FOOD_TYPE, 
--        B.REST_ID, 
--        B.REST_NAME, 
--        B.FAVORITES
-- FROM 
--     (SELECT DISTINCT FOOD_TYPE, 
--                      MAX(FAVORITES) AS "FAVORITES"
--      FROM REST_INFO
--      GROUP BY FOOD_TYPE) A, REST_INFO B
-- WHERE A.FOOD_TYPE = B.FOOD_TYPE
--   AND A.FAVORITES = B.FAVORITES
-- ORDER BY FOOD_TYPE DESC;

-- SELECT FOOD_TYPE, REST_ID, REST_ID, REST_NAME, FAVORITES, VIEWS
-- FROM(
--      SELECT MAX(FAVORITES) AS "FAVORITES", FOOD_TYPE, REST_ID, REST_NAME, VIEWS
--      FROM REST_INFO
--      GROUP BY FOOD_TYPE
--     )
-- ;


-- SELECT FOOD_TYPE, MAX(FAVORITES)
-- FROM REST_INFO
-- GROUP BY FOOD_TYPE;

-- SELECT FOOD_TYPE
-- FROM REST_INFO
-- GROUP BY FOOD_TYPE
-- HAVING FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE);


-- SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
-- FROM
--     (SELECT FAVORITES, FOOD_TYPE, REST_ID, REST_NAME
--     FROM REST_INFO
--     GROUP BY FOOD_TYPE, REST_ID, REST_NAME
--     ORDER BY FOOD_TYPE
--     ) 
-- GROUP BY FOOD_TYPE
-- HAVING FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO);


-- SELECT *
-- FROM REST_INFO;

SELECT F.FOOD_TYPE, I.REST_ID, I.REST_NAME, F.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS "FAVORITES" 
      FROM REST_INFO 
      GROUP BY FOOD_TYPE) F
JOIN REST_INFO I 
ON F.FOOD_TYPE = I.FOOD_TYPE
WHERE F.FAVORITES = I.FAVORITES
ORDER BY F.FOOD_TYPE DESC;







