/*SELECT CAR_ID,   
       ROUND(AVG(END_DATE - START_DATE+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(END_DATE - START_DATE+1),1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;*/

-- SELECT CAR_ID, ROUND(AVG, 1) AS "AVERAGE_DURATION"
-- FROM (SELECT CAR_ID, AVG(NVL(END_DATE - START_DATE + 1, 0)) AS "AVG" 
--       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--       GROUP BY CAR_ID)
-- WHERE AVG >= 7
-- ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC; 

SELECT
    CAR_ID,
    ROUND(AVG(END_DATE - START_DATE + 1),1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    AVG(END_DATE - START_DATE + 1) >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;