-- SELECT ACOUNT, ROUND(BCOUNT / ACOUNT * 100, 2) AS "RATIO" 
-- FROM (
--      SELECT USER_ID, COUNT(*) AS ACOUNT
--      FROM ONLINE_SALE O
--      JOIN USER_INFO U
--      ON O.USER_ID = U.USER_ID
--      WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021'
--      ) A 
-- JOIN (
--      SELECT USER_ID, COUNT(*) AS BCOUNT
--      FROM ONLINE_SALE O
--      RIGHT JOIN USER_INFO U
--      ON O.USER_ID = U.USER_ID
--      WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021'
--     ) B
-- ON A.USER_ID = B.USER_ID

-- SELECT *
-- FROM (
--      SELECT U.USER_ID, COUNT(DISTINCT U.USER_ID)
--      FROM ONLINE_SALE O
--      RIGHT JOIN USER_INFO U
--      ON O.USER_ID = U.USER_ID
--      WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021'
--     ) A
-- JOIN (
--      SELECT O.USER_ID, COUNT(DISTINCT O.USER_ID)
--      FROM ONLINE_SALE O
--      LEFT JOIN USER_INFO U
--      ON O.USER_ID = U.USER_ID
--      WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021'
--      ) B
-- ON A.USER_ID = B.USER_ID


-- SELECT A.YEAR, A.MONTH, A.PURCHASED_USERS, ROUND(A.PURCHASED_USERS / B.CNT, 1) AS "PURCHASED_RATIO"
-- FROM (
--      SELECT EXTRACT(YEAR FROM SALES_DATE) AS "YEAR", 
--             EXTRACT(MONTH FROM O.SALES_DATE) AS "MONTH", 
--             COUNT(DISTINCT O.USER_ID) AS "PURCHASED_USERS"
--      FROM ONLINE_SALE O
--      JOIN USER_INFO U
--      ON O.USER_ID = U.USER_ID
--      WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021'
--      GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE)
--     ) A, 
--     (    
--     SELECT COUNT(USER_ID) AS "CNT"
--     FROM USER_INFO U
--     WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
--     ) B
-- ORDER BY 1, 2;


WITH USER_2021 AS (
    SELECT USER_ID, GENDER, AGE, JOINED
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = 2021
)

SELECT EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
       EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT O.USER_ID) * 1.0 / B.CNT, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_2021 U
ON O.USER_ID = U.USER_ID
CROSS JOIN (
    SELECT COUNT(USER_ID) AS CNT
    FROM USER_2021
) B
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), B.CNT
ORDER BY 1, 2;