-- 서브쿼리에서 GROUP BY 및 HAVING을 사용하여 중복된 HOST_ID를 찾고, 
-- 그 중복된 HOST_ID를 가진 레코드들을 최종 결과에 필터링한다.
SELECT *
FROM PLACES
WHERE HOST_ID IN (
  SELECT HOST_ID
  FROM PLACES
  GROUP BY HOST_ID
  HAVING COUNT(HOST_ID) > 1
)
ORDER BY ID;