-- SELECT *
-- FROM PLACES
-- WHERE HOST_ID IN (
--   SELECT HOST_ID
--   FROM PLACES
--   GROUP BY HOST_ID
--   HAVING COUNT(HOST_ID) > 1
-- )
-- ORDER BY ID;




SELECT P.ID, P.NAME, P.HOST_ID
FROM (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
    ) H
JOIN PLACES P
ON H.HOST_ID = P.HOST_ID
ORDER BY ID;