SELECT
    B.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM
    BOOK A, 
    AUTHOR B, 
    BOOK_SALES C
WHERE
    TO_CHAR(C.SALES_DATE, 'YYYYMM') = '202201'
    AND A.AUTHOR_ID = B.AUTHOR_ID
    AND A.BOOK_ID = C.BOOK_ID
GROUP BY
    B.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY
ORDER BY
    B.AUTHOR_ID ASC,
    A.CATEGORY DESC;
