-- SELECT HISTORY_ID, (DAILY_FEE * DAY) * (100 - NVL(DISCOUNT_RATE, 0)) / 100 AS FEE
-- FROM (
--     SELECT HISTORY_ID, C.CAR_ID, CAR_TYPE, DAILY_FEE, END_DATE - START_DATE + 1 AS DAY,
--     CASE
--         WHEN END_DATE - START_DATE + 1 >= 7 AND END_DATE - START_DATE + 1 < 30 THEN '7일 이상'
--         WHEN END_DATE - START_DATE + 1 >= 30 AND END_DATE - START_DATE + 1 < 90 THEN '30일 이상'
--         WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
--     END AS "DURATION_TYPE"
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
--     INNER JOIN CAR_RENTAL_COMPANY_CAR C
--     ON H.CAR_ID = C.CAR_ID
--     WHERE CAR_TYPE = '트럭'
--     ORDER BY HISTORY_ID
-- ) B
-- LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
-- ON B.CAR_TYPE = P.CAR_TYPE AND B.DURATION_TYPE = P.DURATION_TYPE
-- ORDER BY 2 DESC, 1 DESC;

-- SELECT S.HISTORY_ID, 
-- CASE WHEN S.DURATION_TYPE = '90일 이상' THEN SUM(C.DAILY_FEE *  (100 - P.DISCOUNT_RATE) / 100)
-- WHEN S.DURATION_TYPE = '일 이상' THEN SUM(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100)
-- FROM CAR_RENTAL_COMPANY_CAR C
-- JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
-- ON C.CAR_TYPE = P.CAR_TYPE
-- JOIN SAMPLE S
-- ON P.DURATION_TYPE = S.DURATION_TYPE
-- WHERE 1 = 1
-- AND C.CAR_TYPE = '트럭'
-- GROUP BY S.HISTORY_ID, S.DURATION_TYPE;



-- SELECT S.HISTORY_ID, SUM(C.DAILY_FEE * (S.END_DATE - S.START_DATE + 1) * (100 - P.DISCOUNT_RATE) / 100) AS "FEE"
-- FROM CAR_RENTAL_COMPANY_CAR C
-- JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
-- ON C.CAR_TYPE = P.CAR_TYPE
-- JOIN SAMPLE S
-- ON P.DURATION_TYPE = S.DURATION_TYPE
-- WHERE 1 = 1
-- AND C.CAR_TYPE = '트럭'
-- GROUP BY S.HISTORY_ID
-- ORDER BY FEE DESC, S.HISTORY_ID DESC;

WITH SAMPLE AS (
                SELECT H.HISTORY_ID, 
                       C.CAR_TYPE,
                       (END_DATE - START_DATE + 1) * C.DAILY_FEE AS "FEE",
                       CASE WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
                            WHEN END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
                            WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'
                            ELSE '7일 미만'
                       END AS "DURATION_TYPE"
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                JOIN CAR_RENTAL_COMPANY_CAR C
                ON H.CAR_ID = C.CAR_ID
                WHERE C.CAR_TYPE = '트럭'
               )

SELECT S.HISTORY_ID, FEE * (100 - NVL(P.DISCOUNT_RATE, 0)) / 100 AS "FEE"
FROM SAMPLE S
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON S.CAR_TYPE = P.CAR_TYPE AND S.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, S.HISTORY_ID DESC;