-- 가상의 테이블 만들고, 레프트 조인, 포맷형식(파일모드) 맞춰서 조건 잡고, count: 그룹 지어서 세어야한다.(group by) 
-- *: null값 세고, 컬럼이름인 경우 null값 제외 
-- SELECT D.HOUR, COUNT(D.HOUR) AS "COUNT"
-- FROM (
--      SELECT LEVEL -1 AS "HOUR"
--      FROM DUAL
--      CONNECT BY LEVEL < 25
--      ) D
--  LEFT JOIN ANIMAL_OUTS O
--  ON D.HOUR = TO_CHAR(O.DATETIME, 'FMHH24')
--  GROUP BY D.HOUR
--  ORDER BY D.HOUR;
 
 SELECT 
    HOURS.HOUR,
    COUNT(HOUR_COUNT.ANIMAL_ID) AS "COUNT"
FROM (
    SELECT 
        TO_CHAR(DATETIME, 'HH24') AS "HOUR",
        ANIMAL_ID
    FROM ANIMAL_OUTS
) HOUR_COUNT
RIGHT JOIN (
    SELECT LEVEL - 1 AS "HOUR"
    FROM DUAL
    CONNECT BY LEVEL <= 24
) HOURS
ON HOUR_COUNT.HOUR = HOURS.HOUR
GROUP BY HOURS.HOUR
ORDER BY HOURS.HOUR;