-- Oracle에서는 EXTRACT 함수를 사용하여 날짜의 일부를 추출할 수 있다.
SELECT 
	MEMBER_ID,
  MEMBER_NAME,
  GENDER,
  TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS "DATE_OF_BIRTH"
FROM 
	MEMBER_PROFILE
WHERE
    GENDER = 'W'
    AND EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3
    AND TLNO IS NOT NULL
ORDER BY
    MEMBER_ID;