-- SELECT
--     M.MEMBER_NAME,
--     R.REVIEW_TEXT,
--     TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS "REVIEW_DATE"
-- FROM
--     REST_REVIEW R
-- JOIN
--     MEMBER_PROFILE M
-- ON
--     R.MEMBER_ID = M.MEMBER_ID
-- WHERE
--     M.MEMBER_ID = (
--         SELECT
--             MEMBER_ID
--         FROM
--             REST_REVIEW
--         GROUP BY
--             MEMBER_ID
--         ORDER BY
--             COUNT(*) DESC
--         FETCH FIRST 1 ROWS ONLY
--     )
-- ORDER BY
--     R.REVIEW_DATE,
--     R.REVIEW_TEXT;





-- SELECT *
-- FROM (
--      SELECT MEMBER_ID, COUNT(*) AS "COUNT"
--      FROM REST_REVIEW 
--      GROUP BY MEMBER_ID
--      ORDER BY COUNT DESC
--      FETCH FIRST 3 ROWS ONLY
--      ) C
-- JOIN MEMBER_PROFILE M
-- ON C.MEMBER_ID = M.MEMBER_ID
-- JOIN REST_REVIEW R
-- ON C.MEMBER_ID = R.MEMBER_ID
-- ORDER BY C.MEMBER_ID;


SELECT DISTINCT(M.MEMBER_NAME), R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS "REVIEW_DATE"
FROM (
     SELECT MEMBER_ID, COUNT(*) AS "COUNT"
     FROM REST_REVIEW 
     GROUP BY MEMBER_ID
     ORDER BY COUNT DESC
     FETCH FIRST 1 ROWS ONLY
     ) C
JOIN MEMBER_PROFILE M
ON C.MEMBER_ID = M.MEMBER_ID
JOIN REST_REVIEW R
ON C.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;  













