SELECT DISTINCT C.CAR_ID
FROM 
    (SELECT CAR_ID 
     FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_TYPE = '세단') C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE TO_CHAR(H.START_DATE, 'MM') = '10'  
ORDER BY C.CAR_ID DESC;
