-- SELECT B.CATEGORY, SUM(S.SALES) AS "TOTAL_SALES"
-- FROM BOOK_SALES S, BOOK B
-- WHERE B.BOOK_ID = S.BOOK_ID
--    AND SALES_DATE BETWEEN TO_DATE(20220101, 'YYYY-MM-DD') AND TO_DATE(20220131,'YYYY-MM-DD')
-- GROUP BY B.CATEGORY
-- ORDER BY B.CATEGORY


-- SELECT B.CATEGORY, COUNT(*) AS "TOTAL_SALES"
-- FROM BOOK B
-- JOIN BOOK_SALES S
-- ON B.BOOK_ID = S.BOOK_ID
-- GROUP BY B.CATEGORY, S.SALES_DATE
-- HAVING TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
-- ORDER BY B.CATEGORY;

-- SELECT B.CATEGORY, SUM(S.SALES) AS "TOTAL_SALES"
-- FROM BOOK B
-- JOIN BOOK_SALES S
-- ON B.BOOK_ID = S.BOOK_ID
-- WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
-- GROUP BY B.CATEGORY
-- ORDER BY B.CATEGORY;

SELECT B.CATEGORY, SUM(SALES) AS "TOTAL_SALES"
FROM BOOK B
JOIN (SELECT * FROM BOOK_SALES WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01') S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;

