SELECT A.CATEGORY, A.PRICE AS "MAX_PRICE", B.PRODUCT_NAME
FROM(
    SELECT *
    FROM FOOD_PRODUCT
    WHERE 1 = 1
    AND CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE IN (SELECT MAX(PRICE) 
                  FROM FOOD_PRODUCT 
                  GROUP BY CATEGORY)
    ) A
JOIN FOOD_PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY MAX_PRICE DESC;