-- SELECT PRICE / 10000 AS "PRICE" FROM PRODUCT
-- 7.2

-- SELECT TRUNC(PRICE / 10000) AS "PRICE" FROM PRODUCT
-- 7

-- SELECT TRUNC(PRICE, -4) AS "PRICE" FROM PRODUCT
-- 70000


-- SELECT *
-- FROM PRODUCT;



-- SELECT 
-- CASE 
--     WHEN PRICE = 1 THEN '10000'
--     WHEN PRICE = 2 THEN '20000'
--     WHEN PRICE = 3 THEN '30000'
--     WHEN PRICE = 4 THEN '40000' 
--     WHEN PRICE = 5 THEN '50000' 
--     WHEN PRICE = 6 THEN '60000' 
--     WHEN PRICE = 7 THEN '70000' 
--     WHEN PRICE = 8 THEN '80000' 
-- ELSE '90000' 
-- END AS "PRICE_GROUP"
-- , COUNT(*) AS PRODUCTS
-- FROM (SELECT TRUNC(PRICE / 10000) AS "PRICE" FROM PRODUCT)
-- GROUP BY PRICE
-- ORDER BY "PRICE_GROUP";


-- SELECT TRUNC(PRICE, -4) AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
-- FROM PRODUCT
-- GROUP BY TRUNC(PRICE, -4)  
-- ORDER BY PRICE_GROUP ASC;


SELECT PRICE_GROUP, COUNT(PRICE_GROUP)
FROM(
     SELECT SUBSTR(PRICE, 1,1) * 10000 AS PRICE_GROUP
FROM PRODUCT
WHERE PRICE LIKE '0%'
    OR PRICE LIKE '1%'
    OR PRICE LIKE '2%'
    OR PRICE LIKE '3%'
    OR PRICE LIKE '4%'
    OR PRICE LIKE '5%'
    OR PRICE LIKE '6%'
    OR PRICE LIKE '7%'
    OR PRICE LIKE '8%'
    )
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;

